version: 2
jobs:
  build:
    docker:
      - image: cargox/awscli-docker:python3

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Build Image
          command: docker build -f ~/repo/Dockerfile -t pipefy_test_web_cypress  .

      - run:
          name: Code sniffer
          command: docker run --rm pipefy_test_web_cypress npx eslint .

      - run:
          name: Code formatter
          command: docker run --rm pipefy_test_web_cypress npx prettier --check .

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: personal-context
