export default {
  inputName: 'input[name="customFields.your_name"]',
  txtAreaComment: 'textarea[name="customFields.why_do_you_want_to_work_at_pipefy"]',
  checkBoxOptions: 'input[name="customFields.check_b_option"]',
  labelSelectAnyUser: 'a[name="customFields.select_any_user"]',
  inputFilterUsers: 'input.pp-input.pp-display-block',
  listUsers: '.pp-item-list',
  inputCalendar: '#fake-pipe-field-publicForm-customFields_select_today_s_date-input',
  inputDate: '#date-time-select-date',
  inputTime: '#date-time-select-time',
  actionButtonsCalendar: 'div.pp-date-picker-actions > button',
  selectOptionB: 'select[name="customFields.select_option_b"]',
  inputTimeNow: 'input[name="customFields.what_time_is_it_now"]',
  uploadFiles: 'a.pp-action-add.pp-ico-attachment',
  selectedCountry: 'div.selected-flag',
  countryList: 'ul.country-list',
  inputPhoneNumber: 'input[name="customFields.place_a_phone_number_from_spain_country"]',
  buttonSubmitForm: 'button.pp-btn',
  inputMail: 'input[data-testid="#email-input"]',
};
